#!/bin/bash

if test ${#} -ne 4; then
  echo "Usage: testdemo <corediff binary> <corediff command> <demo name> <core pass>"
  exit 1
fi

corediff=$1
command=$2
demo=$3
pass=$4

# command isnt quotes to allow things such as 'diff square'
"${corediff}" ${command} \
  "demos/ghc-8.8.3/${demo}.pass-${pass}.cbor" \
  "demos/ghc-8.11.0.20200610/${demo}.pass-${pass}.cbor"
